name: TeamSurvival
main: me.chinq.teamsurvival.TeamSurvivalPlugin
version: 1.0.0
api-version: "1.20"
author: Chinq

commands:
  tim:
    description: Timovi u survivalu (TeamSurvival)
    usage: /tim
    aliases: [tik]
