name: TeamSurvival
main: me.chinq.teamsurvival.TeamSurvivalPlugin
version: 3.1
api-version: "1.20"
author: Chinq

commands:
  tim:
    description: Timovi u survivalu (TeamSurvival)
    usage: /tim
    aliases: [team, teams, tik]

  timreload:
    description: Reload config.yml i messages.yml (OP only)
    usage: /timreload
    permission: teamsurvival.reload

permissions:
  teamsurvival.reload:
    description: Dozvola za /timreload
    default: op
  teamsurvival.coinset:
    description: Dozvola za /tim coinset <team> <amount>
    default: op